#!/bin/bash
####################################################################
#
# set the needed environment variables
#
. ../environment_variables
#

# IFC name w/o extension
FC_name='LWN.525'

# Specify atomic masses in the same order as in ph.in file
cat > Atomic_mass <<EOF
    amass(1)=208.980000,
      amass(2)=137.327000,
        amass(3)=47.867000,
	  amass(4)=15.999400,
EOF

# Label for Y (Frequency) axis: THz, cm, or meV
freq=Thz

# Check whether IFC file exists
if [ ! -f $FC_name.fc  ]; then
   echo 'You have no IFC file' $FC_name.fc 'in this directory.'
   echo 'Please find it and copy to this directory'
   exit
fi
